apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-app-content
data:
  index.html: |
    <html>
    <h1>Hello from VERSION 2</h1>
    <p>This is the NEW version of the application</p>
    </html>
